name: Publish Images

on:
  push:
    branches: [master]

jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: k90mirzaei
          password: ${{ secrets.DOCKER_IMAGE_TOKEN }}
      - name: Build all Docker images an push them
        run: |
          make build
          make push
